import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.machines': 'Machines',
    'nav.finder': 'Machine Finder',
    'nav.admin': 'Admin',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Machine Overview',
    'dashboard.totalMachines': 'Total Machines',
    'dashboard.usaMachines': 'USA Machines',
    'dashboard.mexicoMachines': 'Mexico Machines',
    'dashboard.manufacturers': 'Manufacturers',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.viewAllMachines': 'View All Machines',
    'dashboard.machineFinder': 'Machine Finder',
    'dashboard.adminPanel': 'Admin Panel',
    'dashboard.loading': 'Loading...',
    // Machine list page
    'machines.title': 'Machines',
    'machines.search': 'Search',
    'machines.plant': 'Plant',
    'machines.resetFilters': 'Reset Filters',
    'machines.loading': 'Loading...',
    'machines.noFound': 'No machines found',
    'machines.machinesCount': 'Machines',
    'machines.view': 'View',
    'machines.clearFilters': 'Clear Filters',
    'machines.searchPlaceholder': 'Search machine, manufacturer, model...',
    'machines.allPlants': 'All Plants',
    'machines.allManufacturers': 'All Manufacturers',
    'machines.all': 'All',
    'machines.yes': 'Yes',
    'machines.no': 'No',
    'machines.min': 'Min',
    'machines.max': 'Max',
    // Filter group labels
    'filter.machineInfo': 'Machine Info',
    'filter.clampingUnit': 'Clamping Unit',
    'filter.injectionUnit1': 'Injection Unit 1',
    'filter.injectionUnit2': 'Injection Unit 2',
    'filter.robot': 'Robot',
    'filter.additional': 'Additional',
    // Filter field labels
    'filter.force': 'Force (t)',
    'filter.screwDiam': 'Screw ø (mm)',
    'filter.volume': 'Volume (cm³)',
    'filter.hasRobot': 'Has Robot',
    'filter.rotary': 'Rotary:',
    'filter.mucell': 'MuCell:',
    'filter.twoShotAll': '2-Shot: All',
    'filter.twoShotYes': '2-Shot: Yes',
    'filter.twoShotNo': '2-Shot: No',
    // Column group names
    'col.group.machineInfo': 'Machine Info',
    'col.group.machineDimensions': 'Machine Dimensions',
    'col.group.clampingUnit': 'Clamping Unit',
    'col.group.toolConnections': 'Tool Connections',
    'col.group.interfaces': 'Interfaces',
    'col.group.injUnit1': 'Injection Unit 1',
    'col.group.injUnit2': 'Injection Unit 2',
    'col.group.robot': 'Robot',
    'col.group.additionalInfo': 'Additional Info',
    // Column labels - Machine Info
    'col.machine': 'Machine',
    'col.manufacturer': 'Manufacturer',
    'col.orderNum': 'Order #',
    'col.model': 'Model',
    'col.serialNum': 'Serial #',
    'col.year': 'Year',
    // Column labels - Dimensions
    'col.length': 'Length (mm)',
    'col.width': 'Width (mm)',
    'col.height': 'Height (mm)',
    'col.weight': 'Weight (kg)',
    // Column labels - Clamping Unit
    'col.clampingForce': 'Clamping (t)',
    'col.toolCenterDist': 'Tool-center dist (mm)',
    'col.centerNozzle': 'Center Nozzle (mm)',
    'col.centerEjector': 'Center Ejector (mm)',
    'col.fineCentering': 'Fine Center',
    'col.moldHMin': 'Mold H Min (mm)',
    'col.moldHMax': 'Mold H Max (mm)',
    'col.opening': 'Opening (mm)',
    'col.clearH': 'Clear H (mm)',
    'col.clearV': 'Clear V (mm)',
    'col.rotaryTable': 'Rotary Table',
    'col.maxWeight': 'Max Wt (kg)',
    // Column labels - Tool Connections
    'col.tempCircuits': 'Temp Circuits',
    'col.cascade': 'Cascade',
    'col.hotRunnerInt': 'Hot Runner Int',
    'col.hotRunnerExt': 'Hot Runner Ext',
    'col.corePullsN': 'Core Pulls N',
    'col.corePullsE': 'Core Pulls E',
    'col.pneumNozzle': 'Pneum Nozzle',
    'col.pneumEjector': 'Pneum Ejector',
    'col.ejectorStroke': 'Ejector Stroke (mm)',
    'col.ejectorThread': 'Ejector Thread',
    'col.ejectorMax': 'Ejector Max (mm)',
    // Column labels - Interfaces
    'col.mechTool': 'Mech Tool',
    'col.mechRobot': 'Mech Robot',
    'col.elecTool': 'Elec Tool',
    'col.elecHotRun': 'Elec HotRun',
    'col.elecEjector': 'Elec Ejector',
    'col.elecCorePull': 'Elec CorePull',
    'col.elecRobot': 'Elec Robot',
    // Column labels - Injection Units (shared keys)
    'col.screw': 'Screw (mm)',
    'col.shot': 'Shot (cm³)',
    'col.flow': 'Flow (cm³/s)',
    'col.plast': 'Plast (g/s)',
    'col.ld': 'L/D',
    'col.press': 'Press (bar)',
    'col.wt': 'Wt (g)',
    'col.screwType': 'Screw Type',
    'col.nozzle': 'Nozzle',
    // Column labels - Robot
    'col.robotMfg': 'Mfg',
    'col.robotModel': 'Model',
    'col.robotSerial': 'Serial',
    'col.vacuum': 'Vacuum',
    'col.air': 'Air',
    'col.signals': 'Signals',
    // Column labels - Additional
    'col.specialControls': 'Special Controls',
    'col.remarks': 'Remarks',
    'col.plant': 'Plant',
    // Finder
    'finder.title': 'Machine Finder',
    'finder.toolRequirements': 'Tool Requirements',
    'finder.clampingForce': 'Clamping Force (t)',
    'finder.moldWidth': 'Mold Width (mm)',
    'finder.moldHeight': 'Mold Height (mm)',
    'finder.shotWeight': 'Shot Weight (g)',
    'finder.corePulls': 'Core Pulls (Nozzle)',
    'finder.centeringRing': 'Centering Ring Nozzle (mm)',
    'finder.twoShot': '2-Shot Required',
    'finder.rotaryTable': 'Rotary Table Required',
    'finder.search': 'Search',
    'finder.searching': 'Searching...',
    'finder.enterRequirements': 'Enter tool requirements and click Search to find suitable machines.',
    'finder.rankingInfo': 'Results ranked by suitability: Full Match (Green) → Near Match (Yellow) → Not Suitable (Red)',
    'finder.searchingMachines': 'Searching machines...',
    'finder.noResults': 'No machines found matching your criteria.',
    'finder.fullMatch': '✓ Full Match',
    'finder.nearMatch': '⚠ Near Match',
    'finder.notSuitable': '✗ Not Suitable',
    'finder.score': 'Score',
    'finder.needsUpgrading': 'What needs upgrading:',
    'finder.moreGaps': 'and {n} more',
    'finder.plant': 'Plant',
    'finder.year': 'Year',
    'gap.clampingForce': 'Clamping force: {v} t short',
    'gap.moldWidth': 'Mold width: {v} mm short',
    'gap.moldHeight': 'Mold height: {v} mm short',
    'gap.shotWeight': 'Shot weight: {v} g short',
    'gap.corePulls': 'Core pulls: {v} more needed',
    'gap.centeringRing': 'Centering ring: {v} mm mismatch',
    'gap.twoShot': 'No 2nd injection unit',
    'gap.rotaryTable': 'No rotary table',
    'language': 'Language',
    // Admin panel
    'admin.title': 'Admin Panel',
    'admin.tabMachines': 'Machines',
    'admin.tabImport': 'Import Data',
    'admin.tabUsers': 'Users',
    'admin.addMachine': 'Add Machine',
    'admin.searchMachines': 'Search machines...',
    'admin.save': 'Save',
    'admin.saving': 'Saving...',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.confirmDelete': 'Confirm Deletion',
    'admin.deleteWarning': 'This cannot be undone. Type the machine name exactly to confirm:',
    'admin.typeNameHere': 'Type machine name here...',
    'admin.noMachineSelected': 'Select a machine from the list or click Add Machine',
    'admin.markSuspicious': 'Flag as suspicious / needs validation',
    'admin.suspicious': 'Suspicious',
    'admin.suspiciousCount': 'suspicious fields',
    'admin.comments': 'Comments & Notes',
    'admin.addComment': 'Add comment...',
    'admin.submitComment': 'Add',
    'admin.noComments': 'No comments yet',
    'admin.revisionHistory': 'Change History',
    'admin.noRevisions': 'No history yet',
    'admin.by': 'by',
    'admin.newMachine': 'New Machine',
    'admin.required': 'required',
    'admin.sectionMachineInfo': 'Machine Info',
    'admin.sectionDimensions': 'Dimensions',
    'admin.sectionClampingUnit': 'Clamping Unit',
    'admin.sectionToolConnections': 'Tool Connections',
    'admin.sectionInterfaces': 'Interfaces',
    'admin.sectionIU1': 'Injection Unit 1',
    'admin.sectionIU2': 'Injection Unit 2',
    'admin.sectionRobot': 'Robot',
    'admin.sectionMeta': 'Additional Info',
    'admin.restore': 'Restore',
    'admin.deleteRevision': 'Delete entry',
    'admin.confirmDeleteRevision': 'Delete?',
    'admin.wam': 'WAM (Technical Drawing)',
    'admin.wamCurrent': 'Current WAM',
    'admin.wamUpload': 'Upload new WAM',
    'admin.wamHistory': 'WAM Version History',
    'admin.wamNoFile': 'No WAM uploaded yet',
    'admin.download': 'Download',
    'machines.downloadWam': 'WAM',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel de control',
    'nav.machines': 'Máquinas',
    'nav.finder': 'Buscador de máquinas',
    'nav.admin': 'Administrador',
    // Dashboard
    'dashboard.title': 'Panel de control',
    'dashboard.overview': 'Descripción general de máquinas',
    'dashboard.totalMachines': 'Máquinas totales',
    'dashboard.usaMachines': 'Máquinas USA',
    'dashboard.mexicoMachines': 'Máquinas México',
    'dashboard.manufacturers': 'Fabricantes',
    'dashboard.quickActions': 'Acciones rápidas',
    'dashboard.viewAllMachines': 'Ver todas las máquinas',
    'dashboard.machineFinder': 'Buscador de máquinas',
    'dashboard.adminPanel': 'Panel de administración',
    'dashboard.loading': 'Cargando...',
    // Machine list page
    'machines.title': 'Máquinas',
    'machines.search': 'Buscar',
    'machines.plant': 'Planta',
    'machines.resetFilters': 'Restablecer filtros',
    'machines.loading': 'Cargando...',
    'machines.noFound': 'No se encontraron máquinas',
    'machines.machinesCount': 'Máquinas',
    'machines.view': 'Ver',
    'machines.clearFilters': 'Borrar filtros',
    'machines.searchPlaceholder': 'Buscar máquina, fabricante, modelo...',
    'machines.allPlants': 'Todas las plantas',
    'machines.allManufacturers': 'Todos los fabricantes',
    'machines.all': 'Todos',
    'machines.yes': 'Sí',
    'machines.no': 'No',
    'machines.min': 'Mín',
    'machines.max': 'Máx',
    // Filter group labels
    'filter.machineInfo': 'Info de máquina',
    'filter.clampingUnit': 'Unidad de cierre',
    'filter.injectionUnit1': 'Unidad de inyección 1',
    'filter.injectionUnit2': 'Unidad de inyección 2',
    'filter.robot': 'Robot',
    'filter.additional': 'Adicional',
    // Filter field labels
    'filter.force': 'Fuerza (t)',
    'filter.screwDiam': 'Diám. husillo (mm)',
    'filter.volume': 'Volumen (cm³)',
    'filter.hasRobot': 'Tiene robot',
    'filter.rotary': 'Giratorio:',
    'filter.mucell': 'MuCell:',
    'filter.twoShotAll': '2-Shot: Todos',
    'filter.twoShotYes': '2-Shot: Sí',
    'filter.twoShotNo': '2-Shot: No',
    // Column group names
    'col.group.machineInfo': 'Info de máquina',
    'col.group.machineDimensions': 'Dimensiones',
    'col.group.clampingUnit': 'Unidad de cierre',
    'col.group.toolConnections': 'Conexiones de herramienta',
    'col.group.interfaces': 'Interfaces',
    'col.group.injUnit1': 'Unidad de inyección 1',
    'col.group.injUnit2': 'Unidad de inyección 2',
    'col.group.robot': 'Robot',
    'col.group.additionalInfo': 'Información adicional',
    // Column labels - Machine Info
    'col.machine': 'Máquina',
    'col.manufacturer': 'Fabricante',
    'col.orderNum': 'Pedido #',
    'col.model': 'Modelo',
    'col.serialNum': 'Serie #',
    'col.year': 'Año',
    // Column labels - Dimensions
    'col.length': 'Longitud (mm)',
    'col.width': 'Ancho (mm)',
    'col.height': 'Altura (mm)',
    'col.weight': 'Peso (kg)',
    // Column labels - Clamping Unit
    'col.clampingForce': 'Cierre (t)',
    'col.toolCenterDist': 'Dist. centro molde (mm)',
    'col.centerNozzle': 'Centrado boquilla (mm)',
    'col.centerEjector': 'Centrado expulsor (mm)',
    'col.fineCentering': 'Cent. fino',
    'col.moldHMin': 'Alt. molde mín (mm)',
    'col.moldHMax': 'Alt. molde máx (mm)',
    'col.opening': 'Apertura (mm)',
    'col.clearH': 'Luz H (mm)',
    'col.clearV': 'Luz V (mm)',
    'col.rotaryTable': 'Mesa giratoria',
    'col.maxWeight': 'Peso máx (kg)',
    // Column labels - Tool Connections
    'col.tempCircuits': 'Circuitos temp.',
    'col.cascade': 'Cascada',
    'col.hotRunnerInt': 'Canal cal. int.',
    'col.hotRunnerExt': 'Canal cal. ext.',
    'col.corePullsN': 'Kerne boquilla',
    'col.corePullsE': 'Kerne expulsor',
    'col.pneumNozzle': 'Neumat. boquilla',
    'col.pneumEjector': 'Neumat. expulsor',
    'col.ejectorStroke': 'Carrera exp. (mm)',
    'col.ejectorThread': 'Rosca expulsor',
    'col.ejectorMax': 'Exp. máx (mm)',
    // Column labels - Interfaces
    'col.mechTool': 'Mec. herramienta',
    'col.mechRobot': 'Mec. robot',
    'col.elecTool': 'Elec. herramienta',
    'col.elecHotRun': 'Elec. canal cal.',
    'col.elecEjector': 'Elec. expulsor',
    'col.elecCorePull': 'Elec. núcleo',
    'col.elecRobot': 'Elec. robot',
    // Column labels - Injection Units
    'col.screw': 'Husillo (mm)',
    'col.shot': 'Dosif. (cm³)',
    'col.flow': 'Flujo (cm³/s)',
    'col.plast': 'Plastif. (g/s)',
    'col.ld': 'L/D',
    'col.press': 'Presión (bar)',
    'col.wt': 'Peso (g)',
    'col.screwType': 'Tipo husillo',
    'col.nozzle': 'Boquilla',
    // Column labels - Robot
    'col.robotMfg': 'Fabric.',
    'col.robotModel': 'Modelo',
    'col.robotSerial': 'Serie',
    'col.vacuum': 'Vacío',
    'col.air': 'Aire',
    'col.signals': 'Señales',
    // Column labels - Additional
    'col.specialControls': 'Controles especiales',
    'col.remarks': 'Observaciones',
    'col.plant': 'Planta',
    // Finder
    'finder.title': 'Buscador de máquinas',
    'finder.toolRequirements': 'Requisitos del molde',
    'finder.clampingForce': 'Fuerza de cierre (t)',
    'finder.moldWidth': 'Ancho del molde (mm)',
    'finder.moldHeight': 'Altura del molde (mm)',
    'finder.shotWeight': 'Peso de inyección (g)',
    'finder.corePulls': 'Kerne (boquilla)',
    'finder.centeringRing': 'Anillo centrador boquilla (mm)',
    'finder.twoShot': '2-Shot requerido',
    'finder.rotaryTable': 'Mesa giratoria requerida',
    'finder.search': 'Buscar',
    'finder.searching': 'Buscando...',
    'finder.enterRequirements': 'Ingrese los requisitos y haga clic en Buscar para encontrar máquinas adecuadas.',
    'finder.rankingInfo': 'Resultados por idoneidad: Coincidencia total (Verde) → Parcial (Amarillo) → No apto (Rojo)',
    'finder.searchingMachines': 'Buscando máquinas...',
    'finder.noResults': 'No se encontraron máquinas que coincidan con los criterios.',
    'finder.fullMatch': '✓ Coincidencia total',
    'finder.nearMatch': '⚠ Coincidencia parcial',
    'finder.notSuitable': '✗ No apto',
    'finder.score': 'Puntuación',
    'finder.needsUpgrading': 'Qué necesita mejora:',
    'finder.moreGaps': 'y {n} más',
    'finder.plant': 'Planta',
    'finder.year': 'Año',
    'gap.clampingForce': 'Fuerza de cierre: {v} t insuficiente',
    'gap.moldWidth': 'Ancho del molde: {v} mm insuficiente',
    'gap.moldHeight': 'Altura del molde: {v} mm insuficiente',
    'gap.shotWeight': 'Peso de inyección: {v} g insuficiente',
    'gap.corePulls': 'Kerne: {v} más necesarios',
    'gap.centeringRing': 'Anillo centrador: {v} mm de diferencia',
    'gap.twoShot': 'Sin segunda unidad de inyección',
    'gap.rotaryTable': 'Sin mesa giratoria',
    'language': 'Idioma',
    // Admin panel
    'admin.title': 'Panel de administración',
    'admin.tabMachines': 'Máquinas',
    'admin.tabImport': 'Importar datos',
    'admin.tabUsers': 'Usuarios',
    'admin.addMachine': 'Añadir máquina',
    'admin.searchMachines': 'Buscar máquinas...',
    'admin.save': 'Guardar',
    'admin.saving': 'Guardando...',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.confirmDelete': 'Confirmar eliminación',
    'admin.deleteWarning': 'Esta acción no se puede deshacer. Escriba el nombre de la máquina exactamente para confirmar:',
    'admin.typeNameHere': 'Escriba el nombre aquí...',
    'admin.noMachineSelected': 'Seleccione una máquina de la lista o haga clic en Añadir máquina',
    'admin.markSuspicious': 'Marcar como sospechoso / necesita validación',
    'admin.suspicious': 'Sospechoso',
    'admin.suspiciousCount': 'campos sospechosos',
    'admin.comments': 'Comentarios y notas',
    'admin.addComment': 'Añadir comentario...',
    'admin.submitComment': 'Añadir',
    'admin.noComments': 'Sin comentarios aún',
    'admin.revisionHistory': 'Historial de cambios',
    'admin.noRevisions': 'Sin historial aún',
    'admin.by': 'por',
    'admin.newMachine': 'Nueva máquina',
    'admin.required': 'requerido',
    'admin.sectionMachineInfo': 'Información de máquina',
    'admin.sectionDimensions': 'Dimensiones',
    'admin.sectionClampingUnit': 'Unidad de cierre',
    'admin.sectionToolConnections': 'Conexiones de molde',
    'admin.sectionInterfaces': 'Interfaces',
    'admin.sectionIU1': 'Unidad de inyección 1',
    'admin.sectionIU2': 'Unidad de inyección 2',
    'admin.sectionRobot': 'Robot',
    'admin.sectionMeta': 'Información adicional',
    'admin.restore': 'Restaurar',
    'admin.deleteRevision': 'Borrar entrada',
    'admin.confirmDeleteRevision': '¿Borrar?',
    'admin.wam': 'WAM (Plano técnico)',
    'admin.wamCurrent': 'WAM actual',
    'admin.wamUpload': 'Subir nuevo WAM',
    'admin.wamHistory': 'Historial de versiones WAM',
    'admin.wamNoFile': 'Ningún WAM subido aún',
    'admin.download': 'Descargar',
    'machines.downloadWam': 'WAM',
  },
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.machines': 'Maschinen',
    'nav.finder': 'Maschinen Finder',
    'nav.admin': 'Administrator',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Maschinenübersicht',
    'dashboard.totalMachines': 'Maschinen gesamt',
    'dashboard.usaMachines': 'Maschinen USA',
    'dashboard.mexicoMachines': 'Maschinen Mexiko',
    'dashboard.manufacturers': 'Hersteller',
    'dashboard.quickActions': 'Schnellzugriff',
    'dashboard.viewAllMachines': 'Alle Maschinen anzeigen',
    'dashboard.machineFinder': 'Maschinen Finder',
    'dashboard.adminPanel': 'Administrationsbereich',
    'dashboard.loading': 'Lädt...',
    // Machine list page
    'machines.title': 'Maschinen',
    'machines.search': 'Suchen',
    'machines.plant': 'Werk',
    'machines.resetFilters': 'Filter zurücksetzen',
    'machines.loading': 'Lädt...',
    'machines.noFound': 'Keine Maschinen gefunden',
    'machines.machinesCount': 'Maschinen',
    'machines.view': 'Anzeigen',
    'machines.clearFilters': 'Filter löschen',
    'machines.searchPlaceholder': 'Maschine, Hersteller, Modell suchen...',
    'machines.allPlants': 'Alle Werke',
    'machines.allManufacturers': 'Alle Hersteller',
    'machines.all': 'Alle',
    'machines.yes': 'Ja',
    'machines.no': 'Nein',
    'machines.min': 'Min',
    'machines.max': 'Max',
    // Filter group labels
    'filter.machineInfo': 'Maschineninfo',
    'filter.clampingUnit': 'Schließeinheit',
    'filter.injectionUnit1': 'Spritzeinheit 1',
    'filter.injectionUnit2': 'Spritzeinheit 2',
    'filter.robot': 'Roboter',
    'filter.additional': 'Zusätzlich',
    // Filter field labels
    'filter.force': 'Kraft (t)',
    'filter.screwDiam': 'Schnecken-ø (mm)',
    'filter.volume': 'Volumen (cm³)',
    'filter.hasRobot': 'Hat Roboter',
    'filter.rotary': 'Drehtisch:',
    'filter.mucell': 'MuCell:',
    'filter.twoShotAll': '2K: Alle',
    'filter.twoShotYes': '2K: Ja',
    'filter.twoShotNo': '2K: Nein',
    // Column group names
    'col.group.machineInfo': 'Maschineninfo',
    'col.group.machineDimensions': 'Maschinenabmessungen',
    'col.group.clampingUnit': 'Schließeinheit',
    'col.group.toolConnections': 'Werkzeuganbindung',
    'col.group.interfaces': 'Schnittstellen',
    'col.group.injUnit1': 'Spritzeinheit 1',
    'col.group.injUnit2': 'Spritzeinheit 2',
    'col.group.robot': 'Roboter',
    'col.group.additionalInfo': 'Zusätzliche Infos',
    // Column labels - Machine Info
    'col.machine': 'Maschine',
    'col.manufacturer': 'Hersteller',
    'col.orderNum': 'Auftrag #',
    'col.model': 'Modell',
    'col.serialNum': 'Serien-Nr.',
    'col.year': 'Jahr',
    // Column labels - Dimensions
    'col.length': 'Länge (mm)',
    'col.width': 'Breite (mm)',
    'col.height': 'Höhe (mm)',
    'col.weight': 'Gewicht (kg)',
    // Column labels - Clamping Unit
    'col.clampingForce': 'Schließkraft (t)',
    'col.toolCenterDist': 'Werkzeugmittenabstand (mm)',
    'col.centerNozzle': 'Zentrier. Düse (mm)',
    'col.centerEjector': 'Zentrier. Ausw. (mm)',
    'col.fineCentering': 'Feinjust.',
    'col.moldHMin': 'Werkzeugh. min (mm)',
    'col.moldHMax': 'Werkzeugh. max (mm)',
    'col.opening': 'Öffnungshub (mm)',
    'col.clearH': 'Lichtweite H (mm)',
    'col.clearV': 'Lichtweite V (mm)',
    'col.rotaryTable': 'Drehtisch',
    'col.maxWeight': 'Max. Gew. (kg)',
    // Column labels - Tool Connections
    'col.tempCircuits': 'Temperierkreise',
    'col.cascade': 'Kaskade',
    'col.hotRunnerInt': 'Heißkanal int.',
    'col.hotRunnerExt': 'Heißkanal ext.',
    'col.corePullsN': 'Kernzüge Düse',
    'col.corePullsE': 'Kernzüge Ausw.',
    'col.pneumNozzle': 'Pneum. Düse',
    'col.pneumEjector': 'Pneum. Auswerfer',
    'col.ejectorStroke': 'Auswerferhub (mm)',
    'col.ejectorThread': 'Auswerfergewinde',
    'col.ejectorMax': 'Auswerfer max (mm)',
    // Column labels - Interfaces
    'col.mechTool': 'Mech. Werkzeug',
    'col.mechRobot': 'Mech. Roboter',
    'col.elecTool': 'Elek. Werkzeug',
    'col.elecHotRun': 'Elek. Heißkanal',
    'col.elecEjector': 'Elek. Auswerfer',
    'col.elecCorePull': 'Elek. Kernzug',
    'col.elecRobot': 'Elek. Roboter',
    // Column labels - Injection Units
    'col.screw': 'Schnecke (mm)',
    'col.shot': 'Schuss (cm³)',
    'col.flow': 'Fluss (cm³/s)',
    'col.plast': 'Plast. (g/s)',
    'col.ld': 'L/D',
    'col.press': 'Druck (bar)',
    'col.wt': 'Gew. (g)',
    'col.screwType': 'Schneckentyp',
    'col.nozzle': 'Düse',
    // Column labels - Robot
    'col.robotMfg': 'Hersteller',
    'col.robotModel': 'Modell',
    'col.robotSerial': 'Serien-Nr.',
    'col.vacuum': 'Vakuum',
    'col.air': 'Luft',
    'col.signals': 'Signale',
    // Column labels - Additional
    'col.specialControls': 'Sondersteuerung',
    'col.remarks': 'Bemerkungen',
    'col.plant': 'Werk',
    // Finder
    'finder.title': 'Maschinen Finder',
    'finder.toolRequirements': 'Werkzeuganforderungen',
    'finder.clampingForce': 'Schließkraft (t)',
    'finder.moldWidth': 'Werkzeugbreite (mm)',
    'finder.moldHeight': 'Werkzeughöhe (mm)',
    'finder.shotWeight': 'Schussgewicht (g)',
    'finder.corePulls': 'Kernzüge (Düse)',
    'finder.centeringRing': 'Zentrierring Düse (mm)',
    'finder.twoShot': '2-Komponenten erforderlich',
    'finder.rotaryTable': 'Drehtisch erforderlich',
    'finder.search': 'Suchen',
    'finder.searching': 'Sucht...',
    'finder.enterRequirements': 'Werkzeuganforderungen eingeben und auf Suchen klicken.',
    'finder.rankingInfo': 'Ergebnisse nach Eignung: Volle Übereinstimmung (Grün) → Teilweise (Gelb) → Nicht geeignet (Rot)',
    'finder.searchingMachines': 'Maschinen werden gesucht...',
    'finder.noResults': 'Keine passenden Maschinen gefunden.',
    'finder.fullMatch': '✓ Volle Übereinstimmung',
    'finder.nearMatch': '⚠ Teilweise geeignet',
    'finder.notSuitable': '✗ Nicht geeignet',
    'finder.score': 'Bewertung',
    'finder.needsUpgrading': 'Was angepasst werden muss:',
    'finder.moreGaps': 'und {n} weitere',
    'finder.plant': 'Werk',
    'finder.year': 'Jahr',
    'gap.clampingForce': 'Schließkraft: {v} t zu wenig',
    'gap.moldWidth': 'Werkzeugbreite: {v} mm zu wenig',
    'gap.moldHeight': 'Werkzeughöhe: {v} mm zu wenig',
    'gap.shotWeight': 'Schussgewicht: {v} g zu wenig',
    'gap.corePulls': 'Kernzüge: {v} mehr benötigt',
    'gap.centeringRing': 'Zentrierring: {v} mm Abweichung',
    'gap.twoShot': 'Keine 2. Spritzeinheit vorhanden',
    'gap.rotaryTable': 'Kein Drehtisch vorhanden',
    'language': 'Sprache',
    // Admin panel
    'admin.title': 'Admin-Bereich',
    'admin.tabMachines': 'Maschinen',
    'admin.tabImport': 'Daten importieren',
    'admin.tabUsers': 'Benutzer',
    'admin.addMachine': 'Maschine hinzufügen',
    'admin.searchMachines': 'Maschinen suchen...',
    'admin.save': 'Speichern',
    'admin.saving': 'Speichert...',
    'admin.cancel': 'Abbrechen',
    'admin.delete': 'Löschen',
    'admin.confirmDelete': 'Löschen bestätigen',
    'admin.deleteWarning': 'Diese Aktion kann nicht rückgängig gemacht werden. Geben Sie den Maschinennamen ein, um zu bestätigen:',
    'admin.typeNameHere': 'Maschinenname eingeben...',
    'admin.noMachineSelected': 'Wählen Sie eine Maschine aus der Liste oder klicken Sie auf Maschine hinzufügen',
    'admin.markSuspicious': 'Als verdächtig markieren / Validierung erforderlich',
    'admin.suspicious': 'Verdächtig',
    'admin.suspiciousCount': 'verdächtige Felder',
    'admin.comments': 'Kommentare & Notizen',
    'admin.addComment': 'Kommentar hinzufügen...',
    'admin.submitComment': 'Hinzufügen',
    'admin.noComments': 'Noch keine Kommentare',
    'admin.revisionHistory': 'Änderungshistorie',
    'admin.noRevisions': 'Noch keine Historie',
    'admin.by': 'von',
    'admin.newMachine': 'Neue Maschine',
    'admin.required': 'erforderlich',
    'admin.sectionMachineInfo': 'Maschinendaten',
    'admin.sectionDimensions': 'Abmessungen',
    'admin.sectionClampingUnit': 'Schließeinheit',
    'admin.sectionToolConnections': 'Werkzeuganbindung',
    'admin.sectionInterfaces': 'Schnittstellen',
    'admin.sectionIU1': 'Spritzeinheit 1',
    'admin.sectionIU2': 'Spritzeinheit 2',
    'admin.sectionRobot': 'Robot',
    'admin.sectionMeta': 'Zusatzinformationen',
    'admin.restore': 'Wiederherstellen',
    'admin.deleteRevision': 'Eintrag löschen',
    'admin.confirmDeleteRevision': 'Löschen?',
    'admin.wam': 'WAM (Technische Zeichnung)',
    'admin.wamCurrent': 'Aktuelles WAM',
    'admin.wamUpload': 'Neues WAM hochladen',
    'admin.wamHistory': 'WAM-Versionshistorie',
    'admin.wamNoFile': 'Noch kein WAM hochgeladen',
    'admin.download': 'Herunterladen',
    'machines.downloadWam': 'WAM',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
